// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mink.Data;

namespace Mink.Data.Migrations
{
    [DbContext(typeof(MinkDbContext))]
    partial class MinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Mink.Domain.Entities.MinifiedUri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinifiedUriKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrImageUri")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Uris");
                });
#pragma warning restore 612, 618
        }
    }
}
